### ISSUE TITLE
DAO Migration: Gnosis Safe + Snapshot

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/dao#131]
# Problem
Currently, our DAO on mainnet holds all of our funds and controls the `W3API` gov token. It uses Aragon V1 contract, which are very usable and configurable, but highly costly.

For example, creating a payment proposal given current gas costs consumes ~$600 worth of ETH for:
* creation
* 1 vote (cross 10% threshold)
* execute (after 7 day finalization period)

In order to save on gas costs, we'd like to find another DAO solution on mainnet.

# Solution
Gnosis Safe has long been the standard in crypto for secure treasury management. They've recently announced an integration with Snapshot's off-chain voting system [here](https://blog.gnosis.pm/introducing-safesnap-the-first-in-a-decentralized-governance-tool-suite-for-the-gnosis-safe-ea67eb95c34f).

I met with Auryn from Gnosis to discuss SafeSnap's current capabilities + where they're heading. It's all extremely exciting, here is a high level overview:
- Gnosis Safe can be turned into a snapshot DAO using the Gnosis Safe "DAO Module" ([setup guide here](https://github.com/gnosis/dao-module/blob/main/docs/setup_guide.md)). Additionally you'll be adding a Snapshot plugin to interact with your Gnosis Safe's DAO module.
- Votes are made off-chain, and once the proposal is finished you submit the proposal to the DAO for execution.
- Before it can be executed, the question of "did this proposal pass" must be verified using Realitio's escalation game (more on this [here](https://github.com/gnosis/dao-module/blob/main/docs/setup_guide.md#setup-the-realitio-template)).
- Once the escilation game finalizes, it can be executed on-chain through the Gnosis Safe.
- The Snapshot interface supports multiple sequential calls, as well as each call can be made a "delegateCall" meaning the EVM method's instructions would be executed in the context of the Safe's contract.
- Currently the ABI calldata encoding must be done manually outside of Snapshot, but they're working on enabling a nice user-interface for this directly inside of snapshot.
- If you'd like to do something more complex and multi-step (like setup an ENS domain, or use some complex DeFi protocol), encoding calldata manually may be a bit too difficult and unrealistic. In order to help with this, they have a prototype of a dApp that allows you to:
  - Use an dApp
  - Make transactions within the dApp
  - The dApp is running a mainnet fork, which records all transactions being made
  - Once you're done making all modifications, you can export the log of transaction calldata. This can now be easily pasted into Snapshot!
- In addition to the generalized dApp browser described above, you also have access to all of Gnosis Safe's application ecosystem. These Safe-enabled dApps will give you the same experience, where you can perform actions and export the calldata, which can be pasted into Snapshot.

With all of this said, it seems like a completely future proof solution for our DAO, which solves all of our problems. We can:
- Govern the DAO's token using the Gnosis Safe
- Efficiently pass proposals for funding & new token minting (our most common operations)
- Perform complex on-chain actions, like: ENS management, treasury diversification, and multi-address token minting.
- Configure the DAO into the future to suite our needs.

# Our Migration Strategy
In order to make this migration, I'd advice something along the lines of:
- Perform a test DAO migration/upgrade on Rinkeby (or other testnet). This testnet setup + scripts should include:
  - A test Aragon V1 DAO, which would replication our mainnet Aragon V1 DAO (everything configured the same)
  - An upgraded token, which is a fork of our existing governance token. This token contract must be upgradeable, support snapshots, and be initially non-transferable. Marko has done some work on this [here](https://github.com/web3-api/token).
    - The scripts to perform the entirety of this migration process should be as automated as possible, allowing us to repeat on mainnet with minimal chance for error.
  - A new Gnosis Safe w/ DAO Module added
  - Owner of token should be set to Gnosis Safe
  - Test snapshot page pointing to this test Gnosis Safe
  - Transfer of funds from the Aragon DAO to the Gnosis Safe
- Wait until Gnosis DAO or some other high TVL DAO is launched using this. The bug bounty is currently live w/ $50k at stake, but having over $1M in a DAO using this will help improve the security assumptions we can make with this.
- Once we've verified how the migration will take place, and once we've verified other DAOs are "in production" using this, we can make the mainnet migration event happen. I'd propose we migrate X% of the funds initially, and gradually migrate the rest over time.

**Comment by dOrgJelli** [comment]
Additionally, since using the Snapshot interface to send these arbitrary transactions is hard to use (since calldata must be manually encoded + verified), we can make this easier by having "templates" in the DAO repo for common tasks. For example:
- Payout USDT to address `x`
- Mint `x` W3API to addresses `[a, b, c]`

**Comment by morrigan** [comment]
That sounds like an improvement! I am not sure what's the role of using an oracle (Realitio). The contract is the one that verifies the signatures and threshold passing. Is an oracle like an additional check only?

**Comment by dOrgJelli** [comment]
So the signatures aren't actually being verified on-chain @morrigan, instead what's happening is the Realitio oracle is being asked "did proposal X pass on Snapshot at this URL: ...". The Realitio oracle can be configured to work a number of different ways: https://github.com/realitio/realitio-dapp#arbitration-mechanisms

The way I saw demoed was an ETH escalation game, where parties stake ETH on "yes" or "no". There's also support for sending the conclusion to Kleros or some other arbitrator. For the Gnosis DAO, it's likely they'll use GNO as their staking token.

For our DAO, I'm not sure what is the best solution, open to suggestions!

**Comment by orishim** [comment]
Definitely sounds like an improvement, especially the ease of batching multiple complex actions into a single atomic proposal. It looks like we should be able to use the Safe's existing Transaction Builder app, which has a great UX that automatically exposes each function's fields.

I too am not understanding why the setup depends on an external oracle when the DAO's token could just be used for dispute resolution. @dOrgJelli is it possible to use our own token in the escalation game? Also I think this could be better  if actions were executed optimistically, in the sense that they pass by default after a certain amount of time has elapsed without on-chain challenges. If I'm understanding correctly, this setup still requires the same number of on-chain actions as in Aragon: a) create the Realtio question b) stake tokens on the question c) execute the action if possible

If it does end up being the same cost and the only benefit is complex proposals, have we looked into leveraging Aragon Agent for this?

**Comment by morrigan** [comment]
> So the signatures aren't actually being verified on-chain @morrigan 

I see, a wrong assumption on my side then. That's too bad if it can't be connected as it certainly should. Because basically in the end you only trust the oracle and not the DAO. I don't know much about Realitio but I hope it is reliable :)

**Comment by dOrgJelli** [comment]
@morrigan same here, still skeptical myself and will wait to see how the Gnosis DAO pans out for them w/ using Realitio.

@orishim there is an option to use an ERC20 for the escalation game, but it must be transferable as you're staking it for/against on the question. With this in mind, we won't be able to use W3API as it's currently non-transferable.

Yes it does seem like it requires 3 transactions:
1. post question
2. post the "bond" (I think this is the proper terminology)
3. execute the question once it passes

The costs should be much much cheaper than Aragon though, but will ask the Gnosis team to get some mainnet cost estimates to verify.

**Comment by dOrgJelli** [comment]
@morrigan @orishim here are some answers to your questions from Auryn at Gnosis :D

![image](https://user-images.githubusercontent.com/5522128/115755244-24410080-a36b-11eb-980d-4626f12abbf4.png)
![image](https://user-images.githubusercontent.com/5522128/115755398-4b97cd80-a36b-11eb-9fcb-581c2a07c1c0.png)

Links:
https://github.com/gnosis/amb-module
https://docs.google.com/spreadsheets/d/1o8xM1wZ8N2nMXfej9d34M7E7HxP2FgTrG4d8qwuTb9k/edit?usp=sharing
